name: merge dependency update PRs - enterprise support
branding:
  icon: git-merge
  color: green
description: automatically merge dependency update PRs
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token used to perform the merge'
    required: true
  ALLOWED_UPDATE:
    default: patch
    description: 'the type of update to automatically merge. allowed values: "patch", "minor", "major", or "any"'
  MERGE_METHOD:
    default: merge
    description: 'the merge method to use. allowed values: "merge", "squash", "rebase"'
  CUSTOM_BASE_API_URL:
    description: 'A custom base url to use for the github API (for github enterprise)'
runs:
  using: docker
  image: Dockerfile
